### ISSUE TITLE
Not able to infer image

### ISSUE THREAD

**Issue by aayush-gupta15** [Samjith888/EfficientDet-tf-custom_dataset#1]
when I try to do inference 

! python model_inspect.py --model_name=efficientdet-d0 --runmode=infer \
    --max_boxes_to_draw=100   --min_score_thresh=0.4  \
    --ckpt_path='/content/drive/My Drive/efficientdet/efficientdet-d0-scratch'     --input_image='/content/drive/My Drive/efficientdet/input/0.jpg' \
    --output_image_dir='/content/drive/My Drive/efficientdet/output/' \
    --use_tpu=False 

it gives the following error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.

i have tried changing enable_ema value but error remained the same.

**Comment by Samjith888** [comment]
Add the following flag into ur command 

`hparams=“moving_average_decay=0,num_classes=number of classes in ur dataset”`

**Comment by aayush-gupta15** [comment]
I have also tried this..

! python model_inspect.py --model_name=efficientdet-d0 --runmode=infer \
    --max_boxes_to_draw=100   --min_score_thresh=0.4  \
    --ckpt_path='/content/drive/My Drive/efficientdet/efficientdet-d0-scratch'     --input_image='/content/drive/My Drive/efficientdet/input/0.jpg' \
    --output_image_dir='/content/drive/My Drive/efficientdet/output/' \
    --use_tpu=False \
    --hparams="num_classes=13,moving_average_decay=0, image_size=800"

but error remained the same


here my training code:

!python main.py --mode=train_and_eval \
    --training_file_pattern=tfrecord/pascal*.tfrecord \
    --validation_file_pattern=tfrecord/pascal*.tfrecord \
    --model_name=efficientdet-d0 \
    --model_dir=/content/drive/My\ Drive/efficientdet/efficientdet-d0-scratch  \
    --backbone_ckpt=efficientnet-b0  \
    --train_batch_size=8 \
    --eval_batch_size=8 --eval_samples=32 \
    --num_examples_per_epoch=734 --num_epochs=5  \
    --hparams="use_bfloat16=false,num_classes=13,moving_average_decay=0" \
    --use_tpu=False


And how to extract frozen graph?

**Comment by Samjith888** [comment]
Model conversion 

!rm  -rf savedmodeldir
!python model_inspect.py --runmode=saved_model --model_name=efficientdet-d0 \
  --ckpt_path=efficientdet-d0 --saved_model_dir=savedmodeldir \
  --tensorrt=FP32  --tflite_path=efficientdet-d0.tflite
 - -hparams=“moving_average_decay=0,num_classes=number of classes in ur dataset

Actually ur error belongs to the moving average decay .. can u show me the error log ?

**Comment by aayush-gupta15** [comment]
ok.
here it is : -

W0607 18:29:57.785268 139757825877888 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
2020-06-07 18:30:16.289949: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1299, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at /content/EfficientDet-tf-custom_dataset/inference.py:130) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at /content/EfficientDet-tf-custom_dataset/inference.py:130) ]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 418, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 412, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 383, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 202, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/content/EfficientDet-tf-custom_dataset/inference.py", line 618, in inference
    sess, self.ckpt_path, enable_ema=self.enable_ema, export_ckpt=None)
  File "/content/EfficientDet-tf-custom_dataset/inference.py", line 130, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 836, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 886, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 336, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1506, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 70, in get_tensor
    self, compat.as_bytes(tensor_str))
RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1309, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1627, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 74, in get_tensor
    error_translator(e)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 418, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 412, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 383, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 202, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/content/EfficientDet-tf-custom_dataset/inference.py", line 618, in inference
    sess, self.ckpt_path, enable_ema=self.enable_ema, export_ckpt=None)
  File "/content/EfficientDet-tf-custom_dataset/inference.py", line 131, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1315, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at /content/EfficientDet-tf-custom_dataset/inference.py:130) ]]
  (1) Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
	 [[node save/RestoreV2 (defined at /content/EfficientDet-tf-custom_dataset/inference.py:130) ]]
	 [[save/RestoreV2/_301]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 418, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 412, in main
    inspector.run_model(FLAGS.runmode, FLAGS.threads)
  File "model_inspect.py", line 383, in run_model
    FLAGS.input_image, FLAGS.output_image_dir, **config_dict)
  File "model_inspect.py", line 202, in inference_single_image
    driver.inference(image_image_path, output_dir, **kwargs)
  File "/content/EfficientDet-tf-custom_dataset/inference.py", line 618, in inference
    sess, self.ckpt_path, enable_ema=self.enable_ema, export_ckpt=None)
  File "/content/EfficientDet-tf-custom_dataset/inference.py", line 130, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 836, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 886, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 336, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1506, in restore_v2
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()
